### ISSUE TITLE
Component not found 

### ISSUE THREAD

**Issue by ArulGandhi** [cifertech/nRFBox#12]
The mentioned component in the documentation, the nrf24 gtmini is nowhere to be found on the internet. I'm trying to build one of these at home, so please confirm whether it is the same as the nrf24l01. Thanks in advance

**Comment by zRCrackiiN** [comment]
i got them on aliexpress

**Comment by cifertech** [comment]
Hi @ArulGandhi 
in the breadboard version, it's okay to use any type of nRF24, but in the PCB, it should be GT24 mini version. Here is the link for it.

https://www.aliexpress.com/i/4001134750735.html

**Comment by ArulGandhi** [comment]
Thanks a lot for confirming!
