### ISSUE TITLE
spi communication problem

### ISSUE THREAD

**Issue by CtlAltDel6** [cifertech/nRFBox#13]
Breadboard build only works with a single radio attatched to the spi channel. Built with nodemcu wroom32 and using nrf24l01 + modules and breakout boards. I have only a single channel scope so I am unable to watch both ce and csn lines to confirm signal timing and transmition from multiple radios concurrently. Have confirmed spi coms as the issue by running diodes to spi on second and third radios. With that setup I get three radios active in multi jaming and a reliable signal in scanner and analyzer from radio 1, but of course no mesurable signal from radio 2 or 3.
I have tried 2 different proto board variations hoping that my jumper wires were at fault but both have failed.

**Comment by opskrip** [comment]
Hello. I have the same story, but I don't understand it. Can you post a photo of how you did it?

**Comment by CtlAltDel6** [comment]
![20240916_165907](https://github.com/user-attachments/assets/dbd2b0eb-5c3e-451e-b6fc-ee7e3da91f55)
I connected radio 1 straight to the spi bus pins and used three high speed switching diodes to connect both radio 2 and 3 together to the spi pins. This allows for the prepare radio logic to run and returns active on multi ble jammer.
![20240916_165108](https://github.com/user-attachments/assets/e2fffaa4-ba4b-4e25-8e68-52dc39c79b59)

![20240916_165129](https://github.com/user-attachments/assets/389a5be9-7b27-4aba-a37a-44ad67a54f26)

**Comment by CtlAltDel6** [comment]
![20240916_171357](https://github.com/user-attachments/assets/3259 d489-5ca3-4774-8f46-b67818d4b4d4)
Both prototype builds have the same issue

**Comment by CtlAltDel6** [comment]
![20240916_171357](https://github.com/user-attachments/assets/6e846470-763c-4d01-acaf-0f2ed260a713)
Both prototype builds fail in the same way

**Comment by opskrip** [comment]
Thank you very much. I'm new to arduino, so I'm learning how to code through third-party projects. Have a nice day

**Comment by cifertech** [comment]
Hi @CtlAltDel6 
as I tested the project with 3 nRF24, your problem might be a power issue, but the SPI communication is always on the table, I will try to test to see if I can find the problem. If both prototypes fail in the same way, there might be something wrong with my code, but I will try to test it again.

By the way, that's a really impressive prototype.

**Comment by CtlAltDel6** [comment]
![20241229_124956](https://github.com/user-attachments/assets/5d760f07-118f-4b24-bdf8-607914184e4e)
![20241229_125027](https://github.com/user-attachments/assets/b8ff7242-f486-4df6-b651-38d9156bdca4)
Fixed in last update, rushed a messy case. 8.2" long, 3.6" wide, 1.2" depth including antenna. Thank you for all your hard work Cifertech

**Comment by CtlAltDel6** [comment]
Closed, fully functional coms after update
