### ISSUE TITLE
OLED screen not working

### ISSUE THREAD

**Issue by logm1lo** [cifertech/nRFBox#16]
When I complied and flashed the code to esp32 WROOM U and connected the OLED screen to the esp32. The screen won't boot

**Comment by logm1lo** [comment]
this is the output of the serial monitor

![image](https://github.com/user-attachments/assets/9b97de93-fc8b-4667-9b9b-7c66794e2427)

**Comment by logm1lo** [comment]
the fix here is to wait for a couple of hours and turn it back again. Works like a charm

**Comment by Dev-Khrish** [comment]
how did you get it to work ?

**Comment by logm1lo** [comment]
> how did you get it to work ?

I still doesn't understand why I got it to work

**Comment by Dev-Khrish** [comment]
Can you share a bit of schematics/screenshots of wiring or the code you used please

**Comment by logm1lo** [comment]
> Can you share a bit of schematics/screenshots of wiring or the code you used please

Here it is, it's a bit messy tho:
https://github.com/cifertech/nRFBox/issues/17
