### ISSUE TITLE
error: cannot convert 'std::string'

### ISSUE THREAD

**Issue by ahmadjutt611** [cifertech/nRFBox#34]
I have these error in spoofer.cpp in the switches 

switch (deviceType) {
  case 1:
    oAdvertisementData.setManufacturerData(String((char *)dataAirpods).substring(0, 31));
    break;
  case 2:
    oAdvertisementData.setManufacturerData(String((char *)dataAirpodsPro).substring(0, 31));
    break;
  case 3:
    oAdvertisementData.setManufacturerData(String((char *)dataAirpodsMax).substring(0, 31));
    break;
  case 4:
    oAdvertisementData.setManufacturerData(String((char *)dataAirpodsGen2).substring(0, 31));
    break;

**Comment by wajiho23** [comment]
I have the same error: `C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\sourapple.cpp: In function 'BLEAdvertisementData getOAdvertisementData()':
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\sourapple.cpp:78:34: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
   78 |   advertisementData.addData(std::string((char *)packet, 17));
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  |
      |                                  std::string {aka std::__cxx11::basic_string<char>}
In file included from C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEServer.h:22,
                 from C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEDevice.h:21,
                 from C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\sourapple.h:9,
                 from C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\sourapple.cpp:7:
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:36:23: note:   initializing argument 1 of 'void BLEAdvertisementData::addData(String)'
   36 |   void addData(String data);  // Add data to the payload.
      |                ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp: In function 'void setAdvertisingData()':
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:197:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  197 |     oAdvertisementData.setManufacturerData(std::string((char *)dataAirpods, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
In file included from C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEServer.h:22,
                 from C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEDevice.h:21,
                 from C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.h:9,
                 from C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:7:
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:200:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  200 |     oAdvertisementData.setManufacturerData(std::string((char *)dataAirpodsPro, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:203:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  203 |     oAdvertisementData.setManufacturerData(std::string((char *)dataAirpodsMax, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:206:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  206 |     oAdvertisementData.setManufacturerData(std::string((char *)dataAirpodsGen2, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:209:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  209 |     oAdvertisementData.setManufacturerData(std::string((char *)dataAirpodsGen3, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:212:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  212 |     oAdvertisementData.setManufacturerData(std::string((char *)dataAirpodsProGen2, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:215:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  215 |     oAdvertisementData.setManufacturerData(std::string((char *)dataPowerBeats, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:218:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  218 |     oAdvertisementData.setManufacturerData(std::string((char *)dataPowerBeatsPro, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:221:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  221 |     oAdvertisementData.setManufacturerData(std::string((char *)dataBeatsSoloPro, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:224:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  224 |     oAdvertisementData.setManufacturerData(std::string((char *)dataBeatsStudioBuds, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:227:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  227 |     oAdvertisementData.setManufacturerData(std::string((char *)dataBeatsFlex, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:230:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  230 |     oAdvertisementData.setManufacturerData(std::string((char *)dataBeatsX, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:233:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  233 |     oAdvertisementData.setManufacturerData(std::string((char *)dataBeatsSolo3, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:236:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  236 |     oAdvertisementData.setManufacturerData(std::string((char *)dataBeatsStudio3, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:239:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  239 |     oAdvertisementData.setManufacturerData(std::string((char *)dataBeatsStudioPro, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:242:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  242 |     oAdvertisementData.setManufacturerData(std::string((char *)dataBeatsFitPro, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:245:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  245 |     oAdvertisementData.setManufacturerData(std::string((char *)dataBeatsStudioBudsPlus, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:248:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  248 |     oAdvertisementData.setManufacturerData(std::string((char *)dataAppleTVSetup, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:251:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  251 |     oAdvertisementData.setManufacturerData(std::string((char *)dataAppleTVPair, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:254:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  254 |     oAdvertisementData.setManufacturerData(std::string((char *)dataAppleTVNewUser, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:257:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  257 |     oAdvertisementData.setManufacturerData(std::string((char *)dataAppleTVAppleIDSetup, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:260:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  260 |     oAdvertisementData.setManufacturerData(std::string((char *)dataAppleTVWirelessAudioSync, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:263:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  263 |     oAdvertisementData.setManufacturerData(std::string((char *)dataAppleTVHomekitSetup, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:266:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  266 |     oAdvertisementData.setManufacturerData(std::string((char *)dataAppleTVKeyboard, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:269:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  269 |     oAdvertisementData.setManufacturerData(std::string((char *)dataAppleTVConnectingToNetwork, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:272:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  272 |     oAdvertisementData.setManufacturerData(std::string((char *)dataTVColorBalance, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\wajih\Downloads\nRFBox-2.2.1\nRFBox-2.2.1\nRFBox_V2\spoofer.cpp:275:49: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  275 |     oAdvertisementData.setManufacturerData(std::string((char *)dataAirpods, 31));
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 std::string {aka std::__cxx11::basic_string<char>}
C:\Users\wajih\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.7\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~

exit status 1

Compilation error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'`

**Comment by cifertech** [comment]
Hi, use version 1.0.5 of the ESP32 board and follow the instructions.

https://github.com/cifertech/nRFBox?tab=readme-ov-file#-uploading-the-firmware-bin-to-esp32

**Comment by ahmadjutt611** [comment]
can you please give us the library's name and versions like BLE

**Comment by ahmadjutt611** [comment]
![image](https://github.com/user-attachments/assets/d4059b77-c1f1-480c-9fa1-9936878f5345)

after downgrading the esp version. Now shown this error.

**Comment by ahmadjutt611** [comment]
If we install .bin then there is no display on the OLED
